### ISSUE TITLE
from a given root input show all the schema as in betmarduto syriac tool

### ISSUE THREAD

**Issue by PietroLiuzzo** [TraCES-Lexicon/lexicon#1]
See Comprehensive Aramaic Lexicon (http://cal.huc.edu/)  http://cal.huc.edu/oneentry.php?lemma=ktb%20V&cits=all where the answers are also connected to the corpus.

**Comment by eu-genia** [comment]
the beth mardutho sedra tool is here: https://sedra.bethmardutho.org/lexeme/paradigm

**Comment by PietroLiuzzo** [comment]
comment moved to the appropriate issue. requirement renamed.
