### ISSUE TITLE
"An error has been generated by the application."

### ISSUE THREAD

**Issue by wdickhut** [TraCES-Lexicon/lexicon#10]
Entry እመ doesn't work.

**Comment by PietroLiuzzo** [comment]
thanks! I did not take into account there could be entries spanning more than one column...
http://betamasaheft.aai.uni-hamburg.de/Dillmann/?mode=none&q=%E1%8A%A5%E1%88%98&id=L2c08b6c148c540fbbdd89e58f2574bb4
