### ISSUE TITLE
አውድ and አውደ

### ISSUE THREAD

**Issue by abausi** [TraCES-Lexicon/lexicon#17]
There is a small correction to be done, unless this is a general feature to be considered with other  measures: in the structure of the entry, nos 2) and 3) should be indented like 1)

@PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
yes, this is a known issue (#76) with a known cause affecting several hundreds of entries. there is no need to report it for every case, it will be addressed starting during the workshop. this will be kept as example together with the previous

**Comment by PietroLiuzzo** [comment]
#76

**Comment by PietroLiuzzo** [comment]
sorry
