### ISSUE TITLE
input and output will take alternatively fidel or transcription

### ISSUE THREAD

**Issue by PietroLiuzzo** [TraCES-Lexicon/lexicon#5]
lexicon should also provide this as a standalone service, providing transcription of a given string in both directions

**Comment by PietroLiuzzo** [comment]
support only transcription as in BM

**Comment by PietroLiuzzo** [comment]
# Goal 
provide correct transcription alternatives 

# Preconditions
rules for transcription are available in the transcription.html BM tool. they reflect the current BM use but implement a very rudimental javascript technique.

# Example basic flow

**Comment by PietroLiuzzo** [comment]
Also @cvertan has a routine to do this

**Comment by PietroLiuzzo** [comment]
CV= CV or CCV or C 

Consonant vowels can be one of the above see presentation bausi summerschool

**Comment by PietroLiuzzo** [comment]
@abausi I had noted this down on the first day of the summer school, but in Agora I cannot find the slide. Perhaps you could paste here the little schema you had on one of your slides about the consonant-vowel possible combinations?

**Comment by abausi** [comment]
The Ethiopian script (fidäl)

The Ethiopic script is a *syllabic script*:

it is the only syllabic alphabet ever used by Semites;

it is classified among the syllabaries particularly widespread in India 
and Southern Asia;

each syllabic sign indicates sequences of

*consonant+vowel*or *consonant+Ø*;

it does not mark gemination nor Ø vowel:

*<CV> = [CV], [CCV], [C], [CC]*

*26 signs x 7 vowel orders + 4 labiovelars x 5 orders + numerals*

Consonants:

/h/, /l/, /ḥ/, /m/, /ś/, /r/, /s/, /q/, /b/, /t/, /ḫ/, /n/, /ʾ/, /k/, 
/w/, /ʿ/, /z/, /y/, /d/, /g/, /ṭ/, /ṗ/, /ṣ/, /ḍ/ṣ́/, /f/, /p/

ሀለሐመሠረሰቀበተኀነአከወዐዘየደገጠጰጸፀፈፐ

Laryng(e)als (L): /h/, /ḥ/, /ḫ/; /ʾ/, /ʿ/

Vowels:

I phase (length opposition):/Ca Cu Ci Cā Ce Cǝ Co/

II phase (qualitative opposition):/Cä Cu Ci Ca Ce Cǝ Co/

(with laryng(e)als)/La Lu Li La Le Lǝ Lo/

Mergings:

/h/, /ḥ/, /ḫ/ > [h] = <h, ḥ, ḫ>; /ʾ/, /ʿ/ > [ʾ] = <ʾ, ʿ>: La, Lā > [La] 
= <La, Lā]>

/s/, /ś/ > [s] = <s, ś>; /ṣ/, /ḍ/ṣ́/ > [ṣ] = <ṣ, ḍ/ṣ́>



Il 01.11.2017 21:09, Pietro Liuzzo ha scritto:
